name: flutter_device_locale_example
description: Demonstrates how to use the flutter_device_locale plugin.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_device_locale:
    path: ../

flutter:

  uses-material-design: true
